name: Push workflow

on:
  - push

defaults:
  run:
    shell: bash

concurrency:
  group: push-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "16.14.2"

jobs:
  test_and_lint:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2.3.4
      - name: Install node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test
